name: kamera_ocr_1
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_mlkit_text_recognition: ^0.11.0
  camera: ^0.10.5+7
  permission_handler: ^11.0.1
  dotted_border: ^2.1.0
  image_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
